# Generated by Django 5.0.14 on 2026-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('ARTICLE', 'Text Article'), ('PDF', 'PDF Document'), ('RESOURCE', 'Downloadable File'), ('LINK', 'External Link'), ('LIVE', 'Live Session'), ('CODING', 'Interactive Coding Exercise')], default='VIDEO', max_length=20),
        ),
    ]
