import time
from typing import Generator, Dict, Any
from .base import AIProvider

class MockProvider(AIProvider):
    """
    Simulated LLM Provider designed to mimic streaming responses and token tracking metrics
    for testing and local checkout without requiring API Keys.
    """
    def _get_mock_response(self, prompt: str) -> str:
        prompt_lower = prompt.lower()
        
        if "django orm" in prompt_lower:
            return (
                "Django ORM (Object-Relational Mapping) acts as a bridge between your database and Python models.\n\n"
                "Instead of writing raw SQL queries like:\n"
                "`SELECT * FROM courses_course WHERE price > 20;`\n\n"
                "You can query using Python classes:\n"
                "`Course.objects.filter(price__gt=20)`\n\n"
                "**Key features include:**\n"
                "1. Database Independence: Write once, work across PostgreSQL, MySQL, and SQLite.\n"
                "2. Migrations: Django automatically tracks model schema changes and handles schema changes for you.\n"
                "3. Query Optimization: Lazy evaluation means queryset statements don't trigger database requests until you read the results."
            )
            
        elif "summarize" in prompt_lower or "summary" in prompt_lower:
            return (
                "### Lesson Summary Blueprint:\n"
                "1. **Core Concept**: This lesson covers modular routing conventions, path variables, and RESTful best practices.\n"
                "2. **Key Takeaway**: Keep views thin and encapsulate database query filters inside repository classes or services.\n"
                "3. **Practical Implementation**: Use Django REST framework ViewSets to automatically generate CRUD route patterns."
            )
            
        elif "quiz" in prompt_lower:
            return (
                "### Generated Lesson Quiz:\n\n"
                "**Q1: True or False: Django ORM executes querysets immediately upon definition.**\n"
                "* [ ] True\n"
                "* [x] False (Querysets are lazily evaluated)\n\n"
                "**Q2: What is the primary purpose of Django migrations?**\n"
                "* [ ] To compile Python code to machine binary\n"
                "* [x] To sync database schemas with your models\n"
                "* [ ] To load test fixtures into memory"
            )

        elif "flashcard" in prompt_lower:
            return (
                "### Generated Study Flashcards:\n\n"
                "**Card 1: MVC vs MVT**\n"
                "Front: What is the difference between MVC and Django's MVT?\n"
                "Back: In Django, the Controller is handled by the framework itself, templates act as the View, and views act as the Controller.\n\n"
                "**Card 2: Lazy Evaluation**\n"
                "Front: What is lazy evaluation in Django queryset queries?\n"
                "Back: Django querysets do not access the database until they are explicitly iterated or evaluated."
            )

        elif "planner" in prompt_lower or "schedule" in prompt_lower:
            return (
                "### Your Recommended Study Schedule:\n"
                "* **Monday (2 hours)**: Review course curriculum introduction and set up your local development database.\n"
                "* **Wednesday (3 hours)**: Build the core models and create initial database migrations.\n"
                "* **Friday (2 hours)**: Practice writing unit tests for CRUD model operations.\n"
                "* **Sunday (1 hour)**: Quiz review and catch-up buffer session."
            )

        elif "evaluate" in prompt_lower or "feedback" in prompt_lower or "assignment" in prompt_lower:
            return (
                "### AI Assignment Feedback Report:\n"
                "**Strengths**:\n"
                "* Modular code structure with descriptive function names.\n"
                "* Includes basic unit tests for model boundary inputs.\n\n"
                "**Areas for Improvement**:\n"
                "* Lacks error handling wrappers around foreign key model creations.\n"
                "* Suggest wrapping database writes inside a transaction commit helper.\n\n"
                "**Grade Recommendation**: Pass / Acceptable (85%)"
            )

        else:
            return (
                f"Thank you for asking! I've received your query: \"{prompt[:60]}...\".\n\n"
                "This is a rich, context-guided streaming response generated by SkillSphere's "
                "pluggable AI gateway layer. In production, this prompt is routed to the active LLM Provider adapter "
                "to yield answers grounded in your course material."
            )

    def generate(self, prompt: str, system_instruction: str = None, **kwargs) -> Dict[str, Any]:
        text = self._get_mock_response(prompt)
        prompt_tokens = len(prompt.split()) * 2
        completion_tokens = len(text.split()) * 2
        return {
            'text': text,
            'prompt_tokens': prompt_tokens,
            'completion_tokens': completion_tokens
        }

    def generate_stream(self, prompt: str, system_instruction: str = None, **kwargs) -> Generator[Dict[str, Any], None, None]:
        text = self._get_mock_response(prompt)
        words = text.split(" ")
        
        prompt_tokens = len(prompt.split()) * 2
        completion_tokens = len(words) * 2
        
        # Simulate streaming by yielding chunks of words
        chunk_size = max(1, len(words) // 15)
        for i in range(0, len(words), chunk_size):
            chunk_text = " ".join(words[i:i+chunk_size])
            if i > 0:
                chunk_text = " " + chunk_text
            time.sleep(0.05)  # Simulate network latency
            yield {
                'text': chunk_text,
                'done': False,
                'prompt_tokens': 0,
                'completion_tokens': 0
            }
            
        yield {
            'text': '',
            'done': True,
            'prompt_tokens': prompt_tokens,
            'completion_tokens': completion_tokens
        }

    def get_token_count(self, text: str) -> int:
        return len(text.split()) * 2
