from django.urls import path
from .views import (
    RegisterView,
    RegisterVerifyView,
    LoginView,
    LogoutView,
    ProfileView,
    CustomTokenRefreshView,
    EmailVerifyView,
    ResendVerificationView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    UserSessionsView,
    UserPreferenceView,
    AccountDeactivateView,
    DataExportView,
    AccountActivityView,
)
from .security_views import LoginHistoryView, TwoFactorSetupView, TwoFactorVerifyView, NotificationPreferencesView

urlpatterns = [
    path("register/", RegisterView.as_view(), name="auth_register"),
    path("register/verify/", RegisterVerifyView.as_view(), name="auth_register_verify"),
    path("login/", LoginView.as_view(), name="auth_login"),
    path("logout/", LogoutView.as_view(), name="auth_logout"),
    path("refresh/", CustomTokenRefreshView.as_view(), name="token_refresh"),
    path("profile/", ProfileView.as_view(), name="auth_profile"),
    path("profile/preferences/", UserPreferenceView.as_view(), name="auth_profile_preferences"),
    path("profile/delete/", AccountDeactivateView.as_view(), name="auth_profile_delete"),
    path("profile/export/", DataExportView.as_view(), name="auth_profile_export"),
    path("profile/activity/", AccountActivityView.as_view(), name="auth_profile_activity"),
    path("email/verify/", EmailVerifyView.as_view(), name="auth_email_verify"),
    path("email/resend-verification/", ResendVerificationView.as_view(), name="auth_email_resend"),
    path("password/reset-request/", PasswordResetRequestView.as_view(), name="auth_password_reset_request"),
    path("password/reset-confirm/", PasswordResetConfirmView.as_view(), name="auth_password_reset_confirm"),
    path("sessions/", UserSessionsView.as_view(), name="auth_user_sessions"),
    path("login-history/", LoginHistoryView.as_view(), name="auth_login_history"),
    path("2fa/setup/", TwoFactorSetupView.as_view(), name="auth_2fa_setup"),
    path("2fa/verify/", TwoFactorVerifyView.as_view(), name="auth_2fa_verify"),
    path("notification-preferences/", NotificationPreferencesView.as_view(), name="auth_notification_preferences"),
]
