# Generated by Django 5.0.14 on 2026-06-30 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("curriculum", "0003_alter_lesson_lesson_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Multiple Choice (Single Answer)"),
                            ("MULTI", "Multiple Choice (Multiple Answers)"),
                            ("TF", "True / False"),
                            ("SHORT", "Short Answer"),
                            ("FILL", "Fill in the Blank"),
                            ("MATCH", "Matching"),
                            ("ORDER", "Ordering"),
                            ("PREDICT", "Code Output Prediction"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="quizzes/questions/")),
                ("explanation", models.TextField(blank=True, default="")),
                ("difficulty", models.CharField(default="MEDIUM", max_length=20)),
                ("weight", models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ("tags", models.CharField(blank=True, default="", max_length=255)),
                ("partial_credit", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "match_text",
                    models.TextField(
                        blank=True, default="", help_text="For matching questions, the correct match on the right side"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="For ordering questions, correct sequence index")),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="quizzes.question"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("instructions", models.TextField(blank=True, default="")),
                ("passing_percentage", models.IntegerField(default=60)),
                ("max_attempts", models.IntegerField(default=0, help_text="0 for unlimited attempts")),
                ("time_limit", models.IntegerField(default=0, help_text="Time limit in minutes, 0 for no limit")),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("randomize_questions", models.BooleanField(default=False)),
                ("randomize_answer_order", models.BooleanField(default=False)),
                ("negative_marking", models.BooleanField(default=False)),
                (
                    "require_passing",
                    models.BooleanField(default=False, help_text="Require passing before unlocking next section"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")], default="DRAFT", max_length=20
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quizzes", to="courses.course"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz",
                        to="curriculum.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="quizzes.quiz"
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("STARTED", "Started"), ("IN_PROGRESS", "In Progress"), ("SUBMITTED", "Submitted")],
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="quizzes.quiz"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text_answer", models.TextField(blank=True, default="")),
                (
                    "ordering_answer",
                    models.JSONField(blank=True, help_text="JSON list of option IDs in student's order", null=True),
                ),
                (
                    "matching_answer",
                    models.JSONField(
                        blank=True, help_text="JSON dict mapping option ID to matching answer text", null=True
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("is_correct", models.BooleanField(default=False)),
                ("graded", models.BooleanField(default=True)),
                ("flagged", models.BooleanField(default=False)),
                ("time_spent", models.IntegerField(default=0, help_text="seconds spent on this question")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizzes.question")),
                ("selected_options", models.ManyToManyField(blank=True, to="quizzes.answeroption")),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_attempts",
                        to="quizzes.quizattempt",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
