import React, { useState } from 'react';
import { Outlet, Link } from 'react-router-dom';
import { Sparkles, Brain, Award, X } from 'lucide-react';
import { useConfigStore } from '../store/configStore';

export const AuthLayout: React.FC = () => {
  const { DEMO_MODE } = useConfigStore();
  const [isBannerDismissed, setIsBannerDismissed] = useState(() => {
    return localStorage.getItem('demo_banner_dismissed') === 'true';
  });

  const handleDismissBanner = () => {
    setIsBannerDismissed(true);
    localStorage.setItem('demo_banner_dismissed', 'true');
  };

  return (
    <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950 transition-colors duration-200">
      {/* Demo Banner */}
      {DEMO_MODE && !isBannerDismissed && (
        <div className="w-full bg-indigo-50 dark:bg-indigo-950/20 border-b border-indigo-200/40 dark:border-indigo-900/40 px-4 py-2 text-xs flex justify-between items-center text-indigo-700 dark:text-indigo-300 font-light select-none z-50">
          <div className="flex items-center gap-2 max-w-2xl text-left">
            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[9px] font-bold bg-indigo-600 text-white uppercase tracking-wider shrink-0">
              🎓 SkillSphere Demo
            </span>
            <p className="leading-normal">
              You are exploring a public demo of SkillSphere. Some destructive operations are disabled.
            </p>
          </div>
          <button 
            onClick={handleDismissBanner} 
            className="text-indigo-400 hover:text-indigo-600 dark:hover:text-indigo-200 transition-colors p-1 cursor-pointer"
            aria-label="Dismiss banner"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      )}
      
      <div className="flex-1 flex">
      {/* Brand panel - visible on large screens */}
      <div className="hidden lg:flex lg:w-1/2 relative bg-slate-950 overflow-hidden items-center justify-center p-12">
        {/* Grid pattern overlay */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff02_1px,transparent_1px),linear-gradient(to_bottom,#ffffff02_1px,transparent_1px)] bg-[size:24px_24px]" />

        <div className="relative z-10 w-full max-w-md text-white flex flex-col justify-between h-full py-8">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-2.5 transition-opacity duration-150 hover:opacity-90 w-fit" aria-label="SkillSphere Home">
            <img src="/favicon.png" alt="SkillSphere Logo" className="h-8 w-auto" />
            <span className="font-outfit font-extrabold text-xl tracking-tight text-white">
              SkillSphere
            </span>
          </Link>

          {/* Core messages */}
          <div className="my-auto space-y-8">
            <h1 className="text-3xl font-extrabold tracking-tight leading-tight text-white">
              Learn faster. <br />
              Instruct smarter. <br />
              Powered by <span className="text-indigo-400 font-bold">AI Assistance</span>.
            </h1>
            
            <p className="text-slate-400 leading-relaxed text-xs font-light">
              Experience the next-generation SaaS learning platform. Connect with industry experts, attempt customized quizzes generated by AI, and track your development real-time.
            </p>

            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="h-8 w-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center">
                  <Sparkles className="h-4 w-4 text-indigo-400" />
                </div>
                <span className="text-xs font-semibold text-slate-200">Interactive AI Study Tutor</span>
              </div>
              <div className="flex items-center gap-3">
                <div className="h-8 w-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center">
                  <Brain className="h-4 w-4 text-indigo-400" />
                </div>
                <span className="text-xs font-semibold text-slate-200">Automatic Quiz & Assignment Grader</span>
              </div>
              <div className="flex items-center gap-3">
                <div className="h-8 w-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center">
                  <Award className="h-4 w-4 text-emerald-400" />
                </div>
                <span className="text-xs font-semibold text-slate-200">Verifiable Block-Generated Certificates</span>
              </div>
            </div>
          </div>

          {/* Footer */}
          <p className="text-[10px] text-slate-500 font-light">
            © {new Date().getFullYear()} SkillSphere Inc. All rights reserved.
          </p>
        </div>
      </div>

      {/* Form panel */}
      <div className="w-full lg:w-1/2 flex flex-col items-center justify-center p-6 md:p-12 relative bg-slate-50 dark:bg-slate-950">
        <div className="w-full max-w-md space-y-6 animate-fade-in mt-8 lg:mt-0 flex flex-col">
          {/* Logo above the card */}
          <div className="flex justify-center mb-2">
            <Link to="/" className="flex items-center transition-opacity duration-150 hover:opacity-90" aria-label="SkillSphere Home">
              <img src="/logo.png" alt="SkillSphere" className="h-20 w-auto dark:hidden" />
              <img src="/logo_dark.png" alt="SkillSphere" className="h-20 w-auto hidden dark:block" />
            </Link>
          </div>
          <Outlet />
        </div>
      </div>
      </div>
    </div>
  );
};
