# Generated by Django 5.0.14 on 2026-06-30 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Discount")],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage off (e.g. 15.00) or fixed discount amount",
                        max_digits=10,
                    ),
                ),
                ("expiry_date", models.DateTimeField()),
                ("max_uses", models.IntegerField(default=100)),
                ("uses_count", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, coupon is only applicable to this course",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
